
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: product-service
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ghcr.io/akalanka47000/pharmaceutical-product-service:035bf7c4d3b560a1f386b19ec831b3f62985d1aa-1
          envFrom:
            - secretRef:
                name: product-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi
