---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: default
spec:
  encryptedData:
    PORT: AgC7I26T74/V7lZ6k2Tgla1ndBf/8cRJ7G8vukcDMabdCuxgkD+hu70+AXxuNmsPNv7jWdclcm3XdXtW7ubTEAu3WxPiIC1UtfY+g5hcAgGShyqj09EVPq6C+MlPNz76Ug5gfJsfmlfpVNLbXtS6vM4PekLT3TmJ/mFE2oWzFL3GtAwixE8uiaoyGB/UzKg6Y4Wz7lLwU4KAfn1mjVsoIyjY58Op781az8iBHRyqVYo/BTw+UHrWCvrViJN1GoMsegiclaCGHPpbD10efyvMAJKmmK/AAcyPcWEbvO0iiNTsUmp4PHjsLFkQRKMifFY4/VAOkWM21b9fWXYoXh05vwQbuQd3he3UNuXl6QeBH9gsyu1alU+Rj+beYaJ3e8FvtUjwHcsZZzNCui6C7TbSglVS4uHax1uo9BlEYaf1XGkiQLByhYC1xlgMmomRbm07DpCRJ3tfdrAg1GDyy8E8hyCDq5WcQXmpal8wQnAUuN9+Kcf+hE93ZmbghfE7yniXlHnW1KXRa1UKoNvnh2LmiQxrpViL8BAWSRlvYjgzgvlH3A3S9WJPokCPvqSH9bhOa/bj1QMhSLFKxXj3EapPIc9xg34zP2YeCo483ydg1GH6Ap7bYEg0Ywyynzz8vwh9lasMnsNcaBIaxBujOeCs7WeYVtUe38M2h7rOL3SatbTfMa7ohb6M2DkYVTrY3HmOu1Je/ADf
    STRIPE_SECRET_KEY: AgBwDZUUfm7RItcW5dyFFWTwuEpeW/H2Z4UTO5soEI1wTfcWUqn3pMGIaWRknXRka5VbBSperCXg9O95LCoT8j/i8FNn2tyf36wvLG/ROnYC07tfFie//kX54XMFfXrOU2i0rDF2MTpeVG/7DOEYYQHuLHxKI8c9/lgJmIjpx6yZErLOpbfKmC5I5GOtTZSyizPN/dnCkfUaHlJYYDLLg1lkd8LAT9pN/ZfQdcNZf/AX7Y9gV+T4umXeMphmRItM1ArxIjoE46s5jD2UYn1Rrj/sTCMCy4B6DgLsIgpa0Mq178JVTLoiVDal+/G1/TiqXjFUqnyTj+1BnP8w6HOJWAxWXFOPwEoeE+Yv3M8c07+58nu44i0ZOdUOKZ/rn5tzrmvh9OZsTGngByMyc52rkcOIPwR9T/d1AowC8X2VvZp8unRH4hFvLy2foV9Vq8Q5wibceMAPwN1QqXnN1wX5dpKyI30TsBPNF+kLA4Sr7hELJbUFQuRkFDU3D2inONdKGBOHfNw4uN7Q0EX0MkTYUOsNrDYeaD6YcgaP2VIrd54X1xfF6S3KsLQdqYS206qBTA+ONpt7NhM1vXOyIS0viHmubvp6WO3SaRh2MuFs9SSC+axoR8LB79eox1JVqs4xvOkpo/rmP4V7CKLlj4/rMtUoOiFUTruDDlmziJytGwGRa23+pIZo+lGhA1zbQZ3bvIPOG2VXg7s+zPdVFFfHgtKmavnmh/c7nLiUlXy6Kehpugml90vzSlYUjD10QATbeaxavc3In4KJkt0cZcbklFGyF6Ote4jLJ6dSSKzpUY5r99ivXxfJ2kxltT9/HK8vYMgjQUIB/+6Ptr7bLQ==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: default
