---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: default
spec:
  encryptedData:
    PORT: AgCSOhSXZpP+ATG9qYKDi7v8e4fxDe2e1JdcAhwZdyTo7AFYC3m21uGxakPFx9doUC5yKRXHSyyNq/lrsbZmECgZgZvXYBzskCv3xWUKq4+UjEUeHfcUsEB8NrA9FNivLxia4CZ4jLzd/e086nEOYmdbg0UcrAFeVIPtETv+zuhXnSl0ixXfs0qJ9/1tMTJn/irPhviYSHsML4+QRbocPUOBV+EXhU5rHu8S+QDw2qI3upe8aWWdbtUWsX/LTKJ4iH32oD03/jkv8WPZzrxzkS0JmMBClFyUYF84Ca/wL35kOtHyZEyInv+RCa43DglI4pXMBUVSD5dVhkVFk3q1X9yzIvZvYOWsxYdTv4HZIV5f+HTxj7EbiFkOGg/AdKhzEe5iJ1A+/h4wCd+esysao1SDNyOsKmeFHcgJwitThR9RLSJGLn1LUhzANoC0Tz8KVtiTe8K33Z10TKwea3KCK3vZWTzcYMjh/gXvpC5Ax/X+Dsi6YtV7kIXpZHSmDrSpSoMZZbikq1comIDyy3LRv44dL4j4sUf8wNw6nSOGOCVpxZ8R5Rsjsv6D2tDcrRuOmxLJnrpNWHE9vHlXEazw+0Rpn7akUEiMoSMq2cHWsiCrZsem7+HqazOHseGr/rWSOnzFGpy79PAuN5m4A1bXTMCJH0qaFuPmSBnWpHXb0ReT9iQjAiDubajC2E0oKDWZ6dvlNxeJ
    STRIPE_SECRET_KEY: AgA04xn5NDvvFQX4VgB00ghxSvmGtVTNklWU88JBu26C6BibRlMRwml3/9gXgNy/z9z0nWiNACGnDYKHXTgV8xMq4BQAw2k+X8XoD+n4IcMsAouk22eXd5QTXF5YKllxTr2pwdQ3zIJ8TsM7nJGq62S7EYVKDHE86i6gqQq3WqGJRjyUXRVE1nnH2tQIqQsBymRuxlDsCUwm9o5bZzMI5zu2kL6EDVVzsndRcBMczetdpQWyqQrymVyXDd8SgIoiuL9pJpo8Bo6nKzWM5veMq5WGGxS61oQbhIvR/Wyw1bNh4NQxZfUwjKFk+wwkYtQsBYCHCYq1jwAtFMh5lw5LPAf6H1EkJ+/sbmJ4ccwFK97e3SXPe5H2LChl6GsFIYtXxbq+mYQVQk6zZHEYriI2WfCHlFlYXlYKs1frp+gy32MfdQKZT4LTYH3+ln2NYSM3DRO6mRqmOOfUOi0H5Ph7WMsMLbWpGsp5NRTmlG5Gy4wluh+7T2s3PJxkL1m39lR/9USPD50IXpO1YHFXLKaLqMIe+plrP0uJtShEDuUa4tB/VPVZ6An82K1D3PqIIjhcVmrVgSaH+pCbgB+okfqTsm8qBzUMbjvNMoHmlMQte7nLSG6hzqLb4vXMKdG8KinqAdQ096gl85XadtrwmvSc/2BscNQfGEJmyFs2/ZckASmlhIR2CjRtamfXm+2E5QLzfY3tAK5qTlqhyI7j+CD1dyqLm9sCHGMBTziYRmLrLHIIK1cDRas1YY4xrNpIgGBuDNhf2h4s+BmIif9BklHxKLIA+Hms8EWzzGpnynDyedq99fP2HgySehLObIzFcxPJWHVWnRXa0/na90NNjg==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: default
