---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: default
spec:
  encryptedData:
    PORT: AgCHq+oCz5Z58N567lVEm+Y+xlwoDcMkQsR65h9sHUmjspVhVTGxIkfbJIaD+h60ZJIj/INfTOYXf+ydWz9iXZQkDQ6uNPWh46euKcu3CfySNAw2WJW5d+rM4WOjDRTuSyVq7XwosAa+Gzt2H3DYn9MPZLiMWZpfvN+gt4uT4/IrPAv4UON6nRc9IoZAmBYd1ptg6mmeklse+VdUS90IPhn+DVCaQdgc0yGZXGHMf3BPXqb/IS9iRsJcT5R/6Pi0pZ6Rp7DVrErkN50ClclEuj8yGWkV+ntgRebxtd+QjKskH9UgQvz06vpoWfWirc+a2rOHrqrWl6l4pkN+SLyomB4Q8T9loYG40XCCqIvmYAuf6Nomaf9LzO6CW2ddXPdHzxW9WyaRlxxSzqBB/fXjyj+BsNDYDHXH1xCS4CRz/tGiWcR0TYPGjaJ9C0UuRqqt884x/ZMhz5H2HH1Nwr7XM4qj3AxKI8ozl7JEPcvRhQBK+XkQyPKJkZHjm2Bk4mENw9lZUmJCBWoZsTd3VnSi1A6+LY1hddE2abi2ZK7ZajNZO2+Yzk/OsOEwfHBh30LpH+Xd6Q4Aaa13BIaAHduO2VSoGmrzWFIAXHFN56fhci/I1cHamzKpxYzChjW3ntxwweib7kVAxpSboZ1Lxgg6AfzVU+f6yE74w/qIyJfu4R6JshMaeAEhHDwlW0m/LODegeGAN2UX
    STRIPE_SECRET_KEY: AgC+9X2hh1jboSl5USpqtMJmQSnSViNVaVblISkZrRND6nO5ypTpexCkiGfTJetKH2WsiiAHKmZF3MxGFzk/6PS5mXk4RSBHUWt8k4eY/Huu4CqVKE9ULDKJLWbHXzMlCxI7HhkBrlaWWvRjmspKwYuizB3S8Ec+qi8dWbAIF3PVKV+hDSFvUR7tEFgXLq12AmEkN53cn/lKAf6Q9riWWrfdFH/2szFkWB4IzBOutqxqGMPjTYKKPMfslw9OC8qo4mcI+b8Pg19jgB5v1cY7iTR2gB+Ij0v7G3zX396ayDUn2U38jDSqy6H/X5VTffgU4HbiZ1AFlEPohxTqBLZ9HtjiemUWuzg24oB9366Mm8CeI8jAAd8Zy30+7AfJ/9dntkGkTkREIsbzd/zw9X840s6l01XKcWn3qelObxfPGV/sy5/eSat8W++Xz/Zg06sNRZqOfW97FEXxRIi2BQy1b5mpsaATPKeiMBLYb9OP0skBbEonZb4CIAVZZp/Tozhdja90xP5FoM8R1psfvm1LoJOeXjwhvDnrSx53CD2J5WTKCR5hvfARMOn6nFfvAnf2omWIVBB5eky2Wq6WX18J0Q4GlzA/ld7wnKpuvhpZi13OzSQNlVOCnm4V68aW5vKNM2/8J48ga+gfsUofQ00F2501bjyO+3Jp6h7opFf41NQ8BbWZRfugFp/nVZ7LBLdoptoKe3lSsboXLTAIEdgmIB9E/D+W3V+csEWOwJ9WmUwWTCTM5dANJ5PG0tcHffpcKwmW/Brosnn4AHOY8FQ6Z4BTjB3wM60dZvhLotOw/D5PH6ytxcTHBfi2n0Xwy/tZGfh/3l4WW8F61QiSFg==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: default
