---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: default
spec:
  encryptedData:
    PORT: AgB4ezhFSl26p9/VlP2yMnJ6p4cfU+SYgxxuHNhdUY7wM2DYCPBKQnj8E9z/cSCq38VRw59RQRPNhs1olw8HvM9eYNmt/bY8deC7i+YxFrlVst6zHkhloJAeg9fsnFQDk7tsbli0zKkeCa4sLBB0FX9XS2Da0nD6AOMk7py8ZjIpE+bjiqIt3ZLHD7JdMhLjodjoC6U62jIqM8g0yxzI0+B9KoNzj7lIHG/KJ3Su56y0fEcknsXI8ZQAQtlOfGQz95RwBsMlVTCV0hFE2wECHkqTonwpab8dzkNC3VgjhAlofoBiV2Z3AFtQZGgf8b4G2KviIoFAwhrAd9/ssCVnPnkGZDN+ISONEE2NxcDMTUc7oCvdYhu8oJbr+pEIg3cMJyX0dlmr2uj6HPOjYPAVt9McvOIayCEC5gJ0hxhpS2w+xHtsg9RsmckPv7t4gLAP0nxP7kjaZPggKhwsxU8Dl1vYdApkDmczyiJxpiYS0CNIZZqovceboP/PG9ahakvx7DwASRc22H4y0phwJ5GoBeILXOOzP/yfORCAbaXQVGS2jR0fRpv7Qql0RSejx1FrdSXs/fqUT4jHcGuYvY/nXB2KcOFPpK+9xsl1Uq97XqEslLjh7/l3IinnjNSL433hMdT0yphirpVYxmQ4kOrGg6SWmsV/2hdzfNaIzRcuqyMsPPOfWuVLs5bEasE+4V6vc6WNc7aY
    STRIPE_SECRET_KEY: AgBpMO5T55LyyQe6LMl31KNhBiVxRjBBzMZs9FM0Xw9M1YCDW0HU8jptcdoPxpEeNeTZTUNV7iXXZauV7N6Vyv+ocbw6OTxlw9b+qGT4XJmmNvk9P+HFlCtkc8K3QEgp/FJWkPk6N9ZMKvX7KuY5AKcJ6bwAnLRplQ/+DOSh+YqCtvR1+haHNe5E+7hA+wBaMB0vO63QieqlJOll9jsTdNaJBnPXqBwJa0WxPE7gwJTSPs8Lkq8hSUoZUCkqZX17iBqcl5PgRaUSDcHGtL+cmicxPDc2lLZhH9bn5TRved8gnZ5zOY05NqvZWkRTXwEXAvIHuMjGM72bFDtcPaCnZAT1ECS2kIG2v4rvmkc7VwdfddZzidJEx5o5lz8Kk08iJ3qxK8oOAQq7ze+DAKnVpUbkhTxftSztcQ9PfCvgs7ZVpfctU/u1wEoOfMHNF4n+Ty+wQID1y7LfCwA2faQFWGHK5A5jzexx1MauCI0VTV4/JZuCJj3cJ+3VFgZRMpRlzJzACGAYZJKLoxPuFNNLZva0M0woXL+vm4GoVFcZ7Recd9/NU8yKo05RxLlit5US9JUDw1I+3kwfNDF08STPXqWZEn4E321sER8UhO6/eXPXrkwoQr7xra/+l/TUlXNz0yeyDjYPuRPaOH5s2fi6wksqJTU2eonElhfQWeJlfmPfils3rxnPc6tJqJhuIBLpKUE6kA2/GsZSECutydsevwdUhnJcmBjoRxIy8cFfK5mFEF3VPrqjXDQWe4CTD3T7Y9G2qhDA/9Jv982duHjXhQOLl7uak4ICDOUnFk+bMDg9hmYYErp3nECLoczc2re33W73m0zvCwKkCcGDsQ==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: default
