---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: payment-service-secret
  namespace: default
spec:
  encryptedData:
    PORT: AgCi1tNYG/5EsWrMsFASPa0JhI/GxzOncDoW4ten8AruWENZqrs/KRAW0wcAEaZL0UoSP6+UdqJhrujVkIU37+BIsemSzaHNl2BO0QBmQ6NTTbsWDo+h3/dpSq+Yj6/3dQMG0dzoTwd2CA37a4DEmPybw1tmB3cdGLGqt/zPIGfZXC0AQAsxULzBm2W65NXzJpJn2SqLZ1ju6XoAFb+rbACSdPFxXd+J4axbXIIXppOP9T6uHhoZShFr21N3U2/TqaZPy0aid9omiZBadguaMkM4ZBVUY4dfD7U++OAooC4BUBGij3Fnz2rQUqfqDRjVL5qPRBJlmHk4IYL25by2deWe3HnC7mYbXSkkY7jpTHVWiSkro21e7QvN9gbEun8WOeKGKU0QXZlU+KnbAmKHjIYkMDRY/7yrLZUMQrSgvbdllUWcFVNnBvy/SPNXU8RrDANkYYp0wEEXpraYd6jJpdcUHpNjU5RRiF4MlwA+GokJ/e7f45X/Rdr5/ZakTQFeXE84+iLCFTupXISMVtKyZWlpM4yzTZ5b8lpIc53/zTmWIJGrW/NOJ9PoSllCwktqlg1axhG742VwJRwCjSMtkUMou8eSaKf5u3clZy3FUII2vIogcLovJP/+jfjcVBMWXayWchTeOkWy/yKg1WWSiIaQQadGqvOxmObIbMuubHqasMyDKdD89gW0pJAWTk1vw3hSv0V1
    STRIPE_SECRET_KEY: AgAzOKETciuLRamYee09riVcbQ1cP2n8W4wfw9xWby/YPLKi9GoNMoVRDz+NkrRUzXtcMI3KIH9AvNE8J+/wfSB6jiUbMH9mFlEludLAeitIizkapxXyJHKQUoTLB2TU2r2Kq0iyXFdNoh5oxcmd1bMjEa5YnFmc7SnEzNFZL4LcHYn2PYuZKaFEdb3AF1nEHm+8PQe3wwFSJawybt3aueV/0EtGUogoqP61r5zKpatJLDKZf+Gx1T7TWj5Det4i+Uab/V4nBjWSuzrk5nStSY3kzIf3eVJKGvIPBwrbxN2tuGhXQXsnfdPHV1bNRc0waYzcF9Fx6Or2Db2n+/4Zm2N22bpXsRrfAGxYShNROeMzKWrc4qMsh9xhfDbiPdPdTQhMk+3Tu+n+eRn4Re4YomxPnHou3m9FUAXqs4uM8zfj9svDS21oWt99ve1v8FVlO8fSUwQqus6iSd4mvQ7Bq8UH4DwRc5JE7cl3WExCHtwUApzJSaJN9GbQ1Fs6zb0rWu9OTyCGvPl4S9kMOS9oGhuRaY6CV4EODyIo1r3Vj2e9x3KHT7X8kvc3rpYS8bmi5pGHyEkduqH+/WLA6dKN9/qJ9IVwjuV2hnLc9naOEpaWoMZUhqf0jqPpj2axnAEgRTgY9O8aZZVN9JS4vp9PLCyLzCjBV8k3Iwcy+cuQpf2VUH/6+2GFm3BMsH6Ls0cPw6ueUP5ctsrJ3vx0y6+XobFWgfg6iQ5S11N8l+St1JTgW/ySxFg+dgBMFoweyMqdP5KldNO3F59mZvGqPRPMhEDkLKFLedsn4ckLk/jWpkJq/IAIhC/8hv+vncqP5IQMskzzmb8hFCqbk2lwXg==
  template:
    metadata:
      creationTimestamp: null
      name: payment-service-secret
      namespace: default
