
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-service
  labels:
    app: learner-service
spec:
  selector:
    matchLabels:
      app: learner-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: learner-service
      labels:
        app: learner-service
    spec:
      containers:
        - name: learner-service
          image: ghcr.io/mrmihi/edu-hub-learner-service:1a5928f269fc7ae1325d5f0ba8ed7e21a1f1a31e-1
          envFrom:
            - secretRef:
                name: learner-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi
