---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: learner-service-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URL: AgCKgBo8TtHvsoCzwjjScQD471Ms3zFrVVdkmvcWQy2GwhjfAYs6wUqhabRfeem/pOHM9EOBH9bh4E9M9Z0q+zwn7+q0aEC+pvG/LfClyaTuRsH6O+PasjDwXyfNPjfyAnZO5CFBo2qQCKQZgpKNnAaUaq/NGycyM5bdq62nyX04zLu4nTSK9vujjf0c6SiBJTePgVpVgaVCMgV9bIZ7+EmBgUEe9GfXDX+4P+qD3TbyL1MNLQ9UxA8MfD6GkNheIvjXr348Bpl5i0bRgocM10GcH278FKqtaCiSI+XUA+43pqo+hl2yAmsH84NsCZ6c9rMuj3Fu7QC50kqhQ9QFXvMDHCBLPDQ55beHzvB3nGzJhH3p5kX6wXvC9o9jzlmi5XdcN+yX3UcQNSaVJYHM7qbrDeHeABPisET6qGIbphNX/OdHw9fD0nKdeBHuSI/M16dbtWXkgHID4QWDZr027Br72Sutl/dNmyNOgJG+fk7rFCqy56upPiFopMAor/9hfCnxrp3Cfmu+nfRWvI24PHJYi4nP6DKaX4gH63bhYm5BbyLzKdPP/Ok91ULSxw6bofqz3k3L49S4md8ld47cjAxmC9SHY5XwjorbaABva4FOPFFh4Lv/00OgLdPkY9dBLCW2VyzlzS09CYWx0bjRgI00tvCNx1XElfSLc12kVDVXk5tmSH1sHEVCNJmyHOheNGS4V8pNk5RGHWVTQl8dmt7AdELr1ARHYSXi2AbvCtWsW5RgT2TdaN6l3MfZghH8JoNUOD20JsdaQIs2
    PORT: AgDBwe2DQMqpDQ6b4pNdFSn/iaoGjeSAFewCFnmgloQwNK88ucXV6QSi5VPB79UqbAZlQrsRtsjWYfkKAZmhnBZfVA3NwDCy5uecYraju+Uqyro4DJ4GRoUz8JUo1lPobIdAJ26ZfccjhcV2g/4RDRJVjH5ZSbKRqitFVhjBGG24wA8KdUlzf7ehhtFwLISA3PCXiXt6LK7MVnEmx8TJFApr0hr9a5t0K77j02Fe9nHkcQyYPGJ9G5kXbxwWLUlr14FmU05Rj/6rIvDyWJoRdBv/jTpC4usWmLoHu14LFy287eOLpZeE4GOWsboSTj0h7p0Z91FHEqYQHN0PvibjVq7j1mlFfOsHzzig3TH4vIpAIhfmYs862WBwTzN388drdSqOU8IpdCJp9hKbWyX8IgjeaHrL4j8yf2ga9IwVL347XIIdRX4Tm0wauIdtufI8JLgwoPUqgaa1tUiURgWX8vtIwQxb0wqbKsVWqM4tWboXAv2DZVIzTyeiL8zh4CkNag5csvAHIgRn4rju52o1rDrvW4TPExjsKtBFRZ4wKcCPZn0ePpKC+j5HGolzNjvjzpGhC6ORD3bXQ8ibk8t6R8j6Im7mCL7ytLsW58b2qVBaliYHm0viV06R2hCkYR5twmJDQ6Txu0tmvcf+PcXCw0C1B/SZW/w5jWRExkxwkYi3Rd1G+nKIb03MqDYeEs5KUb4as++m
  template:
    metadata:
      creationTimestamp: null
      name: learner-service-secret
      namespace: default
