
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  labels:
    app: feedback-service
spec:
  selector:
    matchLabels:
      app: feedback-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: feedback-service
      labels:
        app: feedback-service
    spec:
      containers:
        - name: feedback-service
          image: ghcr.io/mrmihi/edu-hub-feedback-service:6909b24dbd5f3748956afbecc646d4352c60a419-1
          envFrom:
            - secretRef:
                name: feedback-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi
