---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-service-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URL: AgCc6xymlC8n0Vzx1dvNNqzIYhrmn+Mb9PQly4JrhmjbQBJO/i4K20J+PdwRlFw/e8m1QTcnPR2iPjCLRi7SXMr0qiMUOs+7WDm4irns/Qp0rUusPtUGgS6fBr4YS3t5U2xZt67Q/wWS52X3M+iHow0Y2XNNdKStJEThL8x5oLIlW8scYX8fDAm1KWaRKfCMJXRk91tzRjRCfGHZ7CtG/5out+JUdDBfGitZbpFpjvOZ8Pijd0DFQ2nIrIwshoMdVYY+evkDEnpW3HrYEXH/IjS4a4HdWnHw2MVZhuIVWeL8xE2obB40OuBu4qAGs8JWP+Rn4MoOGYXR4mhCaQKrre8M/lf2oHlI+FY+ydrUhWIIrbtYj8ZNvw18d1MKD053tkkMp+LlZEUnK7zUr02aqbyG6ZiYHeQfdxk76gu3aruzDkRjJopwQbes5HPUJvYjsUMf+Zt81zqDpfLIZ8vk4ejmdSzDZ2yRiTDEXPr/vFh2ABGWlIIxv67ndz+xQKGDR+lVqwxoeFFqFjoAoFawfDuYzKQgEJ8DqGJRKRduCYNaBBzHeoK7rDh8Mv7jbeaaCTvG5gOhKah5EGMLHReMYtqp6fVLeMic8iv6p1qmTXPYpfkJUOzJhfN/sL4cm1aa9buDbOABQ3xGhiNClWGj4FV5i1HtJCmKYebQBNwRhxi9nJ1fnB2pTtY1VwzFCKj/DJr5uX6WW0PX8GAt+AE8AzGjP6L5xdIc74VBrrLukwuZsGvtPZe2kZCx390P4AwKvtk4Ks8brWqOSVPx
    PORT: AgDJAi+Kg+T/vQr1d25ePKy7NjFgoM6Xd7iHpfO8aUuwzTuD7r5XhMzhKeEYQEVch3z5lCOTvK2lg8e9OXn+eBWIIx3hS2MUcM7kXfF6SksHjVxRNl29gHCWUY6Ks0lYfOgT76YmgWKXMkEUx+3teVgBKFUfk4FBIm3mKkbH+5QA4FT9b69vMaK4WcE9KOt3DiIPpPX70hmuupqIXnS0O89nZlP5YYzW7BJ445MnwACntV7TCwh5HjjanPz8vxrSWbKPkF/uxi6uFaUuzB92sPAkiMWlRQLtUwNrF/sJlgTc8QHE2+l4KFkD31cMF0LsAAfCd4iQMSg2LgcAfTJiwrHlSEO6zTdQ7IdLoYu4LOstLuwc12nlO7ypS0LGFq4NrRKYEo383l69Fa3I0vzrT/raQsYzBZwutgq9B2DVtXYsZ0xXd0Hvv5kq4vw/o3ndRDoaIFeWW0M9fA6wcn285q4XnbdgpmDOnfQl+iTg/z5Pj0nFf5pQUn0dUR/ZWHuyvBn8laxb0idkQTXtXcp3K/bb7ToLCAPTSsAeUO0pFFg5Tn2GPzVIEPIgU1NZTmR/GIRK99wihnvJ+2soVr/CRCDI10sKueoz00BSfORtr1a7cLAmEOdGyhaLnmfj+KZhbWqERJRibtZVkyNhu2tws5/JVZ+3QwZuLJ+vSR6wRbmYctuaNfd2WLu1aU0qM8BzmVL05rX2
  template:
    metadata:
      creationTimestamp: null
      name: feedback-service-secret
      namespace: default
