---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-service-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URL: AgBQUDpCRiHnPEehSqLBtMy+hjxVUG4RgfJ4DgeUlLfkRzmV8TmOvnsYhYFz29zEMMILD18Wb6D+lwywiogP7DABc18DqQMeXw+9wPzRvNOxwdQ7sAbNOxRvWad6OPGFJb+653hJmE2urqNoLOWRcxYlLjaAzr+zvX+tkxuzEuZoBJ/348afXVONAjM4K2jSzKAyANGLd7/sf6tkLdRzj8PfavA0NZaRN0c9kgMiuLo60005sQEj7Y3HsS5MVPH0ulQCds4tS9JVjrOtflryKIkw3aRUdcCWmVymFJgdEUfddIDdYmTWhB4o12wFCwOU71OagdtSdBddLz+6/IluQv/MjEUz430lXXeUotVVoeOoJT0JzRYt/guapiwBKSHjF3tRJQTwcTPasvBZNUludkr0SFlW+Rglh12h41rXW47to2cbNipOVhPIeChelwbQUpRLDvtmx4V4EvejE/E1Tatk/R5TcXCOjXaqtqpXZwpmpd1EmzKHqo409PbmkV8ssMPGZJvAhXB7wnF6h5JSd67qTAL7fZ+r90Wje850qJ9sso+ZvwkX6hA3uqhk5W0q9SkM6nrxcVK6mhU8ihpnslPhA/u7Lb0piGxztWdcwF7GOigO3xQBnpELHnjUNJj1W2KIO9pU3SaXlz9NfIdZuepOu+ifP+uK7KwOmoPM879iZWdVnpex+POvYF0rVUEcmHtxJ85lfvox+5sEi6vCLbWVQ9NBs5Jy2UX9hUycUUQcsGt9yW7S61Ly146D5Q+RWY9l9nfkcLeYeIqZ
    PORT: AgBD2587D77d4YqjNvbzIp43YpYBfVKcj48Do8xnyO09Nl2QlPFmd5rh/68XUKJmjoQsouxwre1MRTqNZv9NsWzV0QFWZU/RcvTbSRqHufDcT+6CCoClgZFn4MmWtYdTZGY/9pjY6JKC6urvLYRG0r7VUWgr4Q2QuDJlx6b1qe3KxeajZgD0hlVhBzxrevhaZnWskfLRtZka2tIEJOptQYzZaHez7EEFULENHmZsOUrNaUTTdEPdyV6ZZwCq1iM5lt4y5McJMI5jbum3h1hC2CnzxTrIhr0HWY2sY+sc5bEjBnLpESvba5YcEBM06mCsiPT1vFaRVF7Tyx3F9tlMbBrsWRhKJg2HYaAM5wAAdIu2DUyob49NTRb0c0F2aQjOJzAiFDq9Yi2zgb4/8ejWoVAtANhpRAwh44BczLwTz/fIKdWye2e26oFFBav6ckQsaYAqkwbOR0R5gaOFonbmAR5+eegP+ySFLtkMljYt3fuFdDSLKosrIWR/fHxbLzR19cD4vBJbiV8noXiNszajJeWNI5ZXGTu8sJ8z4zpt3b6oebOprb1ov3m+D8uuU/UyCwF31ahS3kaLrUzu4agC3Kx0hVAsKUIe3jSYPJXc74GPtdO8YJuSbxdiLKExUkugtBUHdND06rVfaRxkrYFZNltrxjngl7gLneh1bNRJO7llXtmrzOvdvQA0waY9kObQ8IJ5A6le
  template:
    metadata:
      creationTimestamp: null
      name: feedback-service-secret
      namespace: default
