---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-service-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URL: AgBFQ9hPMhEo7ysMh9AFpz3vYjNVArn8rLKYiPU8z+rbGPpzbtGY/v2W3Z4Y0NjE5vrQ4pKze5qBX62tAadO3fITO54HM/6Ie10HuJsviIK3M8zJPW9yZe402FKD8XRtMOV7EgNikuRPiN1d2whIBwf6SpR0yZBcUkraLefsITTdo7tfn4oY1e77JRMowyFEpp7I2DRMVjgPdkSuQvxEz0uqd3lnd7STDL9s9W9TMN6ySpOOYJi+iRRoxa2FQSQWSARx2um0aYey8A6RdrVMW2AD1MfDyY7+oTGm76rYJqwjM69wT19PY+cZbTZ7UycEFgS3ErvLJH+qvpV/+9gg8pqqYLiLrMtVY5LaR3HeOMxXp/NWxnmKaOmzN8mCMXqLcXELhC37ukIaJz5p3VNP/a9CrYvekRFLD0tJyvb9Ip/TPIL6bsx4Jgnp2eZYrOpuUrZLRfgMe7xFTcjH7oOHCG3DF004bJMZKhfMSBn4o0tBw0ZfRUyRGDRQNszwZMY9rTWZ6q5L3ST7hQ9/kfUfcJmwksWyzMTU6Uq1SOt2hLwOBzHUxSduNCTsdnruzke6S2wK9xAk5NM2QwldTjajSKzW7plgWmTTgrF7wMb6QELuoCBxQfXrk2SfaYrAIFyHyEfbjvvebzUH7FgVgwdOuyI/O3gspWuFM2HEYorBe+BYCCM+PRfmP9tyAlUBt+QnSWVTRrFP6QfdkA0HhoMFGgBftF3pnEfPs+CxJlLoInBw2mTo1oVnBF7U9WB4MxSyGAL0TZPyr6K2mawE
    PORT: AgAynhzdQx3p7jFdxkALPqdRRxeYtbzLyjdpcWVLZeQebIz7tNUGDt0mzVf5IdpHbarAvehbkO/j2k2ONdGa9nyQUTM42r2vs63W6c1f00tQpb3pSgN5LRizmjNYi6deGYPHV38YzuEgUPFy20eeeXLGk+VBMb1EFSyTUJ4b3hxKramzVRpChVwENiV+phQBRf0Ny7ZA8zEWHMF4nBEClNeL7hYsOMJ9tQ2uS7FSkXi/X7zeTa+TfqhJIT1bPjNs8jhAxAVCbwsRfV3Zy5viCOcF3AvmrsH/S1RbKcP5kCfbO3EACWc4hINHL3KVk+ySUC1C3EYSw78MN6slYKy0GNcEbWwu7/+CYXU65xc6TGtFBCqq4rKt/rYwJrwEP/xrK/l4Xw0hxyq91ayYgtdleV2KsNJWI4jiTUNLdyCQT9DsJg7xv8JA9jRBlPqQdxhh0qzwwMouD/fP2odBKi8YPREzOAMCF/CJqvv8ZEI8ZHbSzCahizX2HPqnLKvedpVo6+K6lxleVG4Rv5i73ycCaUchqc/sZZVGvrM882a8NpbUSks90LuFAQKBUYKftwoYz/4xy6GeKCjoVoFhnSQ7VUKXz9AtnmEcILyphUyRXTVGIkzXQWnQOyrEp6YtxFgqf8xgTQ7ET0BppI63KgZqyh1ZPUUdFZ6Z7g0/eXQBw8/z/sv9EDtXi5E0i+dvSWgGJp7b3tuL
  template:
    metadata:
      creationTimestamp: null
      name: feedback-service-secret
      namespace: default
