---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-service-secret
  namespace: default
spec:
  encryptedData:
    DB_URL: AgC4SlI3Bglv6F1LhLdtxTmf6b8jLc/odPNsFyHVsy+JCyJpakHkM/aEJaVPbg4ADOyizYd6thPLFZemS6+yBtjYj/fzx/VD6KAoIwKdI55ZbvJSIcOom/5D5ScNW6txI1pbOjx+mldGyFn/swDH2zVqnc43d2nehEXPgsSzyQuMSlodPhpjIm/2vgxOPgUCGeNJcbqAll7xHGqCikeazW2sH0mVd4fx5MH78aoNzRyp6fcBQQuYlcQmxH5fCqTr7Z1Nifjs0Ci1uGe3tbkBnOCTr4Z8p0mQt1mv8aDxFAhX6A287hqeMEquniZ7wz/2qSFHZCSE5q8jQt1YPrPcF9+CUPUei8ZKpWfwpCTgKnEujlcimZ3JbaCRRflkKHmMAgxC0jEZa8IY+KjBx6O6tWePoXlMNfidDAOM9t8LgV5xgoWu+EfmUXuop+CNNB/lIR2IeNgzXZJU5c/sJPxts+fRvtWE3AoAON+HNrq+qvNfWNOaXKXcwCXD3pzKdzzP0aYfAVK4q0sCDjkdvcvx2kC60zHQZNYXBB7ObjSsZfXN0wPURIFSzZqryKew6Y6H6syixZ3WsFtcCJo6YNfJDkU4+Q/gieE7Dkpc1z0nGGwbuQbeVIrU10wSmuyJf/D+y8mmEKT0YPGTosfAqAU5PcaHlA7I8ZFTa55GDmpeIVfYsRY2H4jxuIR4ednpyJ31vLxhtD+tshWtO179uCnlwujhonDw+gbn6CF0Qo4RWWcjWqGEo5VXs4KIS0p4AIjhea12bD1dYAL2g0C8
    PORT: AgBlgpSKhVz8xh5VkoOlD5GGC7j6PbyxDChoy372ZJZGgZLvmntbAXNo7XCuwmdhExYhv1rTlU7bPQGick5Un1c0oho3baTREHsQ67bx9UEUEkgSk0DBAzhCNmM8hsZTup/Hy4362jjHn7j4AZ+xOlt3bZ/q21KUBApW7F2ClMLbLKOmT9f/FNkvlJh+JuicNO/LkFlIOg0oM9u5642ON+gGZ7xMzXVGJC64ArpA0BnuMvPrpgPc+Xs8duygvaRFhYauinaeC0cKurbrK+IE23Iqu/mBWmf2WfnJZa0tpCaVrPnaGl+aWITLI4PCkeonqVThpv7bo079EiROa1SafGx7b4xPHAupE4TqzLmV7EkeEYS1B1lDH2TbhK8Z2G9kDLnHIoMvda0Rpu4D2bV9cyysYOAasllOWaARJFldkmInL4K/YSwmS8Md91SUeKlCZbambSq24P7x4dTWs0Cot26cBESHPHFgYBnhvJEhO4GUFuukxCCWsPPff0nzJkeZ6iI7nMhsLZOcNRTdP7KQuMm1PcBVJOShs+oEQxTg9vCATCHQHvuiivE7RZe87+KOhiqmw/F+YuEKEmSSf4Ni5p3k8T7mgGKn1V3G7ei0WU5+Ik/ZHfUYxwbULbRONuKvUukxCH/ko4XyUduPLvkVpl54I6+WjyK9DQvMt8NtuqV1vLnQr4rCdshHOb+w+QI3+wUUHoWX
  template:
    metadata:
      creationTimestamp: null
      name: admin-service-secret
      namespace: default
