apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: default
data:
  policy.default: role:admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  namespace: default
