---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: course-service-secret
  namespace: default
spec:
  encryptedData:
    DB_URL: AgAtnF3es3Y5JyxNRfgsdWzdECPdmBSPvtaCwrL9BltMbhOBE+n2CT9u2xRqFucr0W3GozrT9d+vS/yD/Q/YcsmSg0AdeUW4PCJGKMgxPkBTgo2r5r69miR8fzK1TmUabRErXuyhQCpjFQ9hr3wft1nE6I9bPwvhiZhZJ5vtSoY2fAh/mpzYzztbS7vHQwmRz3gNPFTHqyssKjMizJvlttw+ugjwqw+p0vAdJefrPOwXzp3J95eQrzSe2kOKj4MuFOLBfH7U/DztJGj+u4EmGI0oa3q8rqs3JJPMhAZECm6qBFsHSTmi4FzExJFZIhoNtwtu2jmEI2HKR1A1yfsh88odDUvStBX+UVKSZOTQJkexZ9m7ZiE0mzxEYvj19blkz9JBu94iACbhrSUDpvuBaUzDFBmzyvvO4BTuWB4g14R/6akte7ChFG+N5MtAbBSekFcMu5I9RxPtTE4Re/SIIR3WoePbI2ui81C16Qc6eQkzy8j8ZtTTAmjPLF7Q+EMAm69AXiJ9ghlC0O8dgAV4QDB7xmXpR8g3yt7UGi/9XxLu1aElFXxnOnXH532Sz/w93d22tWrPOfDh1Z68oStve7AQcGEpOTd53Src+5d3XdY4y6LZL7BrnI6XzsFvquKyeGJVguxvBnL23BVxqnIzAarmXwUiKNt9ehsV5ERy5Z0EO1XUls9aj+yIMZCPPVCRuIu65oMPR4j6OUOI14/kU3rsHUDsIXt+bnW1GTgNAHp6L10McB+eykBWohGKAH9qKkraEz1aiiuKKvV9
    PORT: AgApCGzTQHPpJrR2mHJRSZWYfSGsxbYw8QMkbS89XBpfWq1IZONtYTx57a8K6x8KjAy7bj5K6bot+ViIeihPSIkun0H90Rw6vwNVQUqEgrKapz7HJVe/VVPiCTQwsQtooixkmeWrIvk4Ylui4kF+7znhddmJ9i0NAvxwWXkVj5JDUipPya7xp82b0IlRIZiC1CFgC7BbnwFFkNe5o8aAlgz96w/Abqs3KSQkhJ9sfXVhMS9jIck2GsSbhpwIJKMSovxhRObAeGdF/KgI1ZITxjm1efGIMSsJeIifnlhnOpUE3Z53t63pE7XHSRyi04XpDDGt1JvHQL5mkuF2CMvdjoLUT2TGdxl7NXN6zlEpvpmm+8JhDiyL4x+vm1yn2uj+dqzbrHlsvuG5BkfyUg64iMD5xgqTegMzuY4VO5e2yz5JMwfQ+HeBaLXkvkoCK2Lu7wTvRlEcHk8DXhpuDN1OfRTu3vUCsIVq5wYiqyJ/0zSTi0GF0ISMcH1ZGLe2EM5FWc53XS1cyt6lbgVHjsL8ybeWIPqBBr7au0lo85DVQ5VKuCT4nI2qyeSi+AXdMRFe8WA81bb+3e2eg9Z27kfo3LkK8FPs+yaggXja+mHEmORNMg6egBbpPeqiyGESZm6ffNkryz2dly8n84iI8uLAvQ0eC4qvzOsJwHO8eNXW9jyk9PoL28RjcyRpt/fILwI8iqZ18j6L
  template:
    metadata:
      creationTimestamp: null
      name: course-service-secret
      namespace: default
