---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: course-service-secret
  namespace: default
spec:
  encryptedData:
    DB_URL: AgAy3LGQwJ0LsS6Na4ejrB1377wo5AgdQw4cHYUjVKnGUE7Jqyj2TusH4Z0EG7ixqgjUoIN2SpSwg0rOdVeJCWZPLkSY75e903HYH1Lt4NIvb5vxIqMJFHkaRzFPu6f5PGeZvMGT2p6EdFxHneG6UXEaoAFTf56oonMJy70FjYEOSW+cDABW+YVrSRFhjzjdHv7zvE1xxt7W7EbpySOmHsUesqV2U0DG6HhjLS8YTZbPixGBfsQzlzA/wMp5RGmAAEjPWl1U/ZNzF6W9yOveaGClQEbZiSUO6ZImnv4Kueo5O9Q6ZD+YGROkLLTIh3vJNwTQPFDMMRpOFsNlA2Ml4QcHbE2qclbP0snJ/zOqnC0n7j0VMFeCW8Y6zmCJWZJqhZy6NNBJFlbOSHEHiGQ7XDTTx0OJjXFAvpEZRCU+TlB2z/dKCedoQPEQqCvb0yZK4H43S0lvlTHfyZHqxsiClZPF181JF+vC1IewZ0tqFcto7TiaO3afS6X3y9wdFXgtEfBr32MPjJrmJJyv2oA85ABwgabq0sTQS2GU26n5klKoZunXp61pc0itLpNTfcl2RzAVEoTwQikuu5FqOV1aZQm+Z9pNLamlncanxe69MkR1LKQ/XS+H2PgHl1DqVCYWm07HzH50k+o5rwYqdf6OUjJkZMHztYV8BTx5sRD1FhbYUm7ghiajOgwbxbjz0W02qJ0bCBHNGdNNa+9MQpd4dn3nqJdABoXzhB8baz6au+NM0RagRa7uL6tivVXOKUWQuS1ytydrcJQ5qfDs
    PORT: AgCKvqO3FtF3Qua+9k719eglMj/wnxxGQgzjtqF92gamsDODkjToYO5hzHrkqB88D3gwHuNS7a+rb0OunsNIpfU2g83dU4W7TuM6htjgZZAaFr2xE+zLWl9az7bwerNWKUzxJ+cRYx+it0MG1Itc3KBhuxiOZNYTvX2173gbR8nzbXGhoWDDD+sJQCgxe3cYZlQqwsIWIbVACYLHTg711hvxfTiiBuPh6digNJBv2gLYsDcq+pIWbt2M6yD2LkGX7+bljGSptw6eVR9hC9XnschjOojxrgQiJlGfUN7/8IFwpMzipkqDy60PfOjnLRpf3r+DCMIGTNa6j/bBhKz6wr8YUdpDYFxKQ8M9r/vTKlKW+MWWWeV9J3TkLfyBb1q37oYTLZ6N8UyDvUagkr63KUhBbZ4mAhb7w8TsZZs1aPhC1yDP1argHSvViQBEE7qpF0/7KymKViGnrDspAac+dnKIzLVbtw+CmOCzyT8B3aopBCArTHYrUyixxAaTPB4QhzCAPIuDZ/OACeyv5C7QKXw8T/JL160zVb9wql7eb5xpGlFCXDXoCyUgE+pyqBTy3V89K+GZ6tIk4mLtdvIEs0VDYCXYIgz+wLkZ/1i8IJ3AmE0j35hzXFQWcVtpxN+dZ1hnIPYVTmsvHywjgd1jJbCoZ8td2riW2vS8VrdMyEK0920WTX5lAh9KrDv6v6RUgRquXO5W
  template:
    metadata:
      creationTimestamp: null
      name: course-service-secret
      namespace: default
