---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: course-service-secret
  namespace: default
spec:
  encryptedData:
    DB_URL: AgBJpthdvsjwjhWH/WjGuadwJ/TkSwEhvtXUFfo03yTQaCJadqJuIbWb7AAldBgwYxMh7R9fc1rirt5WsRV3k1/AV2r2VQQSxz3HnB0Vvb/NjPHiIPm0gnXlFqwxCwoOSa7ay5grghg9+HjTpg/8h9YCb5iDlv/tZ4wXZD6ZRQtqdlHJ+3nL5UUSCF6F+NwQGKSHnv/1NweHHZI02iMnoEyRajbwSmmHhkR0gFgBUVj+GLLhqLPNjuHLzlpYj0RrZ8h3iv4klLCCxXjzHouxkQimXkTUAaAB+F3TjexJlGC2ixKKOy9iJuKFOo0M+GBg1J70S5tnH6YS/PO4G8ig5MN2Jr+GgTbNXe36agmlvMLQBucF0WCnh1lO7g9ZRC6TMO+fXzRLTi0S3rG540yKIFqpKuQPhYbIWXcPxxFnkxoBym06R5292C8NjXtbC7W7uPK7UC6jY8Kmwll7PdQiTj58haM4vJOcMvIUzSnIxXFllNZlAFOf2kOy0+VPZfq1SS5wMDLKSl7+sZz8wZXerQQ9z6EijIIhPz+I/l79NYORQeu09ve8nUDDyCGNwYN6QJqBwmVE7IzAtX4MShZOR7mnijxoTBgQlJ0N0anTIgDlcsoHJ4IAPTRN5CtqpIKqNTUAuGyA4Z7puSI4TzoKbFn00sNRRiSWD6ksT5fnkfoTr+4oNFcNcaOwUWU+4Z0ZssbINaWNCYaPwBxtMlv4sUtR42iGUk4e9Y92i9h+M9MkNCy0DPCvLpQ4i+nJ0OYvnbs0gUM6DSfvW5hj
    PORT: AgAiX6jIViv83SEb8Aw4cJkU6CL1E5qCVl2qtNIMraIfUHwN5eIvqFOfRcIdUJ4mwC7Xe4gPySKFk8N/3q4PLQZy/ja+JhRiOAhdbGcHV8ks4J31fGD/mOn/zILqxSbEVkjqrl2OCntrKbmBLQGM6BiV/G4tfnw1OBDk1XVv37VVcGFrvtKFvFNMWd0gPyRW7roHU2F4pDovXO0VrpQk06+irjD+ovuqp/z0sB4Rf1ywy/IUGyRJmCer9DPss/3D5nU2JdDDKovkBJOL5uQEdTpDX1rg4lRbumctpxcr7Xp3m5L0A6Hjo/XFHxXJYDx+PXrSkrlwW0fmyJn3GdaLY2t34cqFL7AoesGv6sM+c2b1/WoIK5+0eERObJ/EYkhqp4Du1UJefMAi6W34iEzDPBqNjmHcb2ylcapsWHCX9Asz07eY/B2YoOYzXDNxRVk2cEfkEHJH0kg7w7ftu0wBInCcPz2Ms3Flkqykj1aOhfooKx2pY2l2Pug+ps5Q57mmFqGzusIv9nLcv5CLYx8yULhuIDDcfyxrlVi7l7YdPwTYbeWQgyvRYltKI3PNqy8gISjKqotVBFxKZTnuUttktjAdYAni44MEDtdFotX+a0grWzacSIn8Uw/gP2KcqH1MgcTfKfcVWKpzYKlYATq7RoZbIhGH572K0mMjkZoxA1f9O0dNbfNDGoyWIHn9RPSGlP5+0KVs
  template:
    metadata:
      creationTimestamp: null
      name: course-service-secret
      namespace: default
