
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: auth-service
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/mrmihi/edu-hub-auth-service:d8ef840f4fd1379c4febb6b5ce3f43956083938c-1
          envFrom:
            - secretRef:
                name: auth-service-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /system/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 20m
              ephemeral-storage: 1Gi
              memory: 128Mi